@startuml cup-detection-system
!include <C4/C4_Container.puml>

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Cup Detection System Container Diagram

Person(user, "User", "Office employee using the kitchen.")
Person(office_manager, "Office Manager", "Manages office cleanliness and monitors incidents.")
Person(system_admin, "System Administrator", "Configures and maintains the system.")

Container_Boundary(cup_detection_system, "Cup Detection System"){
Container(rinse_detection, "Rinse Detection Service", "Posix Shell", "Makes a distinction between rinsing and leaving a cup.")
Container(facial_recognition, "Facial Recognition", "Posix Shell", "Identifies users from camera feed.")
Container(gdpr_compliance, "GDPR Compliance Service", "Posix Shell", "Anonymizes gdpr non-compliant data.")
Container(notification_service, "Notification Service", "Posix Shell", "Sends notifications to users.")
ContainerDb(data_storage, "Data Storage", "Posix Shell", "Stores data, images and video snippets of incidents.")
Container(public_board, "Public Board", "Posix Shell", "Displays recent offenders.")
Container(gdpr_deletion, "GDPR Deletion Service", "Posix Shell", "Allows gdpr deletion of user data.")
Container(timestamp, "Timestamp service", "Posix Shell", "Gets a real time timestamp.")
Container(dashboard, "Dashboard", "Posix Shell", "Overview for office managers.")
}

Rel(user, notification_service, "Receives notifications.")
Rel(user, public_board, "Views board.")

Rel(office_manager, dashboard, "Views incident logs and manages users.")

Rel(system_admin, cup_detection_system, "Configures system settings.")

Rel(public_board, data_storage, "Displays public offender board.")
Rel(public_board, dashboard, "Displays public offender board.")

Rel(dashboard, data_storage, "Stores incident data.")

Rel(notification_service, gdpr_compliance, "Sends incident notifications.")
Rel(data_storage, gdpr_compliance, "Stores incident data.")
Rel(data_storage, gdpr_deletion, "Deletes data if requested.")

Rel(data_storage, timestamp, "Gets timestamp.")

Rel(gdpr_compliance, rinse_detection, "Identifies users.")
Rel(rinse_detection, facial_recognition, "Identifies users.")
@enduml