@startuml protenderizer-component
!include <C4/C4_Component.puml>

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

title Protenderizer Component Diagram

Person(user, "User", "User of the system")

System_Ext(ted, "TED Open Data API")

Container_Boundary(main_system, "Main System") {
    Container_Boundary(application, "Protenderizer") {
        Container(data_retrieval, "Retrieval Module", "Python")
        Container(data_preprocessing, "Preprocessing Module", "Pandas")
        Container(data_storage, "Storage Module", "Python")
        Container(data_visualization, "Visualization Module", "Python")
        Container(machine_learning, "Machine Learning Module", "ML stack")
        Container(cli, "Command Line Interface", "Click")
    }
    ContainerDb(database, "Data Store", "PostgreSQL")
}

Rel(user, cli, "")
Rel_Right(cli, data_retrieval, "")
Rel_Right(data_retrieval, ted, "")
Rel(data_retrieval, data_preprocessing, "")
Rel(cli, machine_learning, "")
Rel_Left(cli, data_visualization, "")
Rel_Down(machine_learning, data_storage, "")
Rel(data_preprocessing, data_storage, "")
Rel_Right(data_storage, database, "")
Rel(data_visualization, data_storage, "")

@enduml