@startuml protenderizer-component
!include <C4/C4_Component.puml>

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()

title Protenderizer Component Diagram

Person(user, "User", "User of the system")

System_Ext(ted, "TED Open Data API")

Container_Boundary(main_system, "Main System") {
    Container_Boundary(application, "Protenderizer") {
        Container(data_retrieval, "Retrieval Module", "Python")
        Container(data_preprocessing, "Preprocessing Module", "Pandas")
        Container(data_storage, "Storage Module", "Python")
        Container(data_visualization, "Visualization Module", "Python")
        Container(machine_learning, "Machine Learning Module", "ML stack")
        Container(cli, "Command Line Interface", "Click")
    }
    ContainerDb(database, "Data Store", "PostgreSQL")
}

BiRel(user, cli, "")
BiRel_Right(cli, data_retrieval, "")
BiRel_Down(cli, data_preprocessing, "")
Rel_Right(ted, data_retrieval, "")
BiRel(data_retrieval, data_preprocessing, "")
BiRel(cli, machine_learning, "")
BiRel(cli, data_visualization, "")
Rel_Left(data_storage, machine_learning, "")
BiRel_Down(data_preprocessing, data_storage, "")
BiRel_Right(data_storage, database, "")
Rel_Up(data_storage, data_visualization, "")

@enduml